// <auto-generated />
using System;
using DSU21.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DSU21.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.13");

            modelBuilder.Entity("DSU21.Models.Pirate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ShipId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ShipId");

                    b.ToTable("Pirates");
                });

            modelBuilder.Entity("DSU21.Models.Ship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("PirateID")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PirateID");

                    b.ToTable("Ships");
                });

            modelBuilder.Entity("DSU21.Models.Pirate", b =>
                {
                    b.HasOne("DSU21.Models.Ship", null)
                        .WithMany("Pirates")
                        .HasForeignKey("ShipId");
                });

            modelBuilder.Entity("DSU21.Models.Ship", b =>
                {
                    b.HasOne("DSU21.Models.Pirate", "Captain")
                        .WithMany()
                        .HasForeignKey("PirateID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Captain");
                });

            modelBuilder.Entity("DSU21.Models.Ship", b =>
                {
                    b.Navigation("Pirates");
                });
#pragma warning restore 612, 618
        }
    }
}
